### ISSUE TITLE
Replace log4j 2.14.1 by something no-vulnerable

### ISSUE THREAD

**Issue by egore** [JetBrains-Research/anti-copy-paster#14]
The prebuilt package contains a log4shell vulnerable version of log4j 2.x Please update this to 2.17.1 or newer. See https://logging.apache.org/log4j/2.x/ for details

**Comment by onewhl** [comment]
@egore, thank you!
@Olenek, please take a look at it.

**Comment by areyde** [comment]
We have updated the tool and added the link to the newly built version to the README. Thank you!
