### ISSUE TITLE
Download still old version

### ISSUE THREAD

**Issue by hschenke** [JetBrains-Research/anti-copy-paster#23]
Hi guys,
here you describe to install this plugin : 

"AntiCopyPaster requires IntelliJ IDEA of version 2022.2 to work. To install the plugin:
    Download the pre-built version of the plugin from [here](https://drive.google.com/file/d/1hueIpbxUxr_IPCNtww7Htc2ckqzTcsPE/view?usp=sharing);"

But it's still the old version for Intellij 2021.3 and not as written 2022.2 ?
There are another download link or other possibility to get ?
Kind regards
Holger

**Comment by onewhl** [comment]
Hi @hschenke,
Thank you! We have updated the link to the plugin in README: [link](https://drive.google.com/file/d/1zc1Sx7slvEVfaXcvPx19OP-tUHs6qOWZ/view?usp=sharing).

**Comment by hschenke** [comment]
Thanks @onewhl it works now 👍
